 --Q1: Customers Above Average Spend..Find customers whose total spend is greater than average customer spend..Multi-step required

  select customer_id, sum(order_amount) as total_spend 
  from orders
  group by customer_id
  having sum(order_amount) > ( select avg(total_spend)
                         from (select customer_id, sum(order_amount) as total_spend
						 from orders
						 group by customer_id) as temp


--Q2: Orders Above Overall Average Amount..Find all orders where order_amount is greater than average order amount.
select order_id, order_amount 
from orders
where order_amount > ( select avg(order_amount)
                      from orders )


--Q3: Top Spending Customers (Above 1000)..Find customers whose total spend is greater than 1000.
--Solve using: Subquery..Then try using CTE
select customer_id, total_spend
from ( select customer_id, sum(order_amount) as total_spend
       from orders
       group by customer_id
	   ) as temp
where total_spend > 1000;

--CTE(WITH)
WITH temp as(
             select customer_id, sum(order_amount) as total_spend
             from orders
             group by customer_id)
select customer_id, total_spend
from temp
where total_spend > 1000;



--Q4: Customers with Latest Order After Feb 2023..Find customers whose latest order date is after '2023-02-01'..Think aggregation + filtering
select customer_id, MAX(order_date) as latest_order
from orders
group by customer_id
having MAX(order_date) > '2023-02-01';


--Q5: Customers Who Never Cancelled Any Order..Find customers who have placed orders but never cancelled..Trick: exclusion logic
select distinct customer_id
from orders
where customer_id NOT IN(select customer_id
from orders
where order_status = 'CANCELLED' 
);

--Q6: Customers Whose Spend is Above Their Country Average
--Find customers whose total spend is greater than average spend of their country..Multi-level aggregation
select c.customer_id
from customers c
join orders o on c.customer_id = o.customer_id
group by c.customer_id, c.country
having sum(o.order_amount) > (
    select avg(total_spend)
    from (
        select c2.country, c2.customer_id, sum(o2.order_amount) as total_spend
        from customers c2
        join orders o2 on c2.customer_id = o2.customer_id
        group by c2.country, c2.customer_id
    ) as temp
    where temp.country = c.country
);


--Q7: Second Highest Order Amount..Find the second highest order_amount..Avoid simple LIMIT tricks (think properly)
select max(order_amount) as second_highest
from orders
where order_amount < (
    select max(order_amount)
    from orders
);

--Q8: Customers with More Orders Than Average Customer..Find customers whose total number of orders is greater than average orders per customer.
select customer_id, count(*) as total_orders
from orders
group by customer_id
having count(*) > (
    select avg(order_count)
    from (
        select customer_id, count(*) as order_count
        from orders
        group by customer_id
    ) as temp
);

--Q9: Revenue of Top 2 Customers..Find total revenue generated by top 2 highest spending customers..Step-wise thinking required
select sum(total_spend) as revenue
from (
    select top 2 customer_id, sum(order_amount) as total_spend
    from orders
    group by customer_id
    order by total_spend desc
) as temp;

--Q10: Customers Who Contribute to Top 50% Revenue..Find customers who contribute to top 50% of total revenue
with temp as (
    select customer_id,
           sum(order_amount) as total_spend
    from orders
    group by customer_id
),
ranked as (
    select *,
           sum(total_spend) over (order by total_spend desc) as running_total,
           sum(total_spend) over () as overall_total
    from temp
)
select customer_id, total_spend
from ranked
where running_total <= 0.5 * overall_total;